### ISSUE TITLE
Not necessarily an issue

### ISSUE THREAD

**Issue by bsparrow** [pbenson/flextech-library-website#11]
This isn't an issue but give me some feedback on this. For the flextech logo at the top left of the index.html page maybe we could link it to the school's website: flextech-hs.org.

**Comment by akazanjian** [comment]
I think that could be a good idea, but only if it was easy to get back to the library page from FlexTech's home page.

**Comment by bsparrow** [comment]
We could have it open FlexTech's home page in a new tab so we  don't need to worry about redirecting back to the library.

**Comment by crasyleg73** [comment]
good idea
