### ISSUE TITLE
CSS dilemma

### ISSUE THREAD

**Issue by Blatherskite** [pbenson/flextech-library-website#17]
As I recently committed the revised Minecraft page, I realize that only this HTML document linked to 'style.css' before I changed it. All other documents used 'browse_style.css', which explains the visual discrepancy between the one page and all others.

Is 'style.css' even going to be used at this point, or do we scrap it?

EDIT: the landing page (index.html) uses that stylesheet and probably needs it, my bad.

**Comment by lucasstanesa** [comment]
I have seen a lot of additions (300+) in the last week to style.css specifically. Waiting for input from design team on this

**Comment by agrecascino** [comment]
Hi.

**Comment by Mfield16** [comment]
The Style.css sheet was used specifically the Index page. There was no intent of using it else where to my knowledge.
