### ISSUE TITLE
Create a Git Best Practices page.

### ISSUE THREAD

**Issue by pbenson** [pbenson/flextech-library-website#19]
Either to the website, or in the documentation. This should cover what to do when you begin working for the day, what to look for when committing and syncing, and what to do when you are done working.

**Comment by Blatherskite** [comment]
I've created a [page](https://github.com/pbenson/flextech-library-website/wiki/Good-Git-Practices) on the wiki for it. I encourage everyone to add to it and generally participate in the wiki.
