### ISSUE TITLE
Less inline css

### ISSUE THREAD

**Issue by mtello** [pbenson/flextech-library-website#29]
I see that some of these commits use inline CSS. Is that sound?

I know that it will be a lot of work if you want to change the styling of certain elements later on.

I would propose that you guys use separate files for styling, or at least use a style tag in the head instead. 

That way, at least you won't be duplicating work, and if bugs arise, it will be an easier fix.

**Comment by lucasstanesa** [comment]
I think a lot of these pages were taken from templates for a css framework, and a lot of the inline styles/scripts are leftover

**Comment by mtello** [comment]
Yes, but the issue is actual code in the tag :( 
Something like this `<h1 style="color:blue;margin-left:30px;">This is a heading.</h1>`

**Comment by mtello** [comment]
I don't know about that. These are recent commits, of a line or two.

**Comment by mtello** [comment]
Or even stuff like this, that are basically a bug
html```
<h2><font color="#E6E6E6"> FlexTech Online Library</font></h2>
```
