### ISSUE TITLE
No Link to Minecraft on the tutorials page

### ISSUE THREAD

**Issue by SoggySocks** [pbenson/flextech-library-website#5]
http://127.0.0.1:50001/tutorial.html 
We need a link to minecraft.html

**Comment by crasyleg73** [comment]
IT is needles to point this out, so I am pointing this out. Adding such a link would decrease school productivity and distract potentially successful students, causing them to be potentially unsuccessful students. the ultimate ruin would follow from such a change. so I recommend you make the change.
