### ISSUE TITLE
Multiple Arduino tutorials

### ISSUE THREAD

**Issue by Blatherskite** [pbenson/flextech-library-website#7]
arduino-tutorial.html and arduino-tutorial-1.html both exist. Involved content authors, please get this sorted out.

**Comment by crasyleg73** [comment]
I will discuss this with the other content author, and get it sorted out. Right now I am thinking this way: 
the main Arduino page should be in the main directory, and all subpages and tutorials will be in the tutorials directory. that is the way I'm thinking right now anyway.

**Comment by crasyleg73** [comment]
opening a new topic related to this
