### ISSUE TITLE
Commit Names and Summaries

### ISSUE THREAD

**Issue by akazanjian** [pbenson/flextech-library-website#9]
Please do not make commits with nonsense names or summaries such as 'a' or 'gggg'. If you make a commit, the name and summary of the commit should be useful to the reader. We need to be able to know which commits we can revert to, should an issue appear.

**Comment by lucasstanesa** [comment]
This is not apparrent or obvious for initially, but it is an extremley useful tool. Commit messages should at least be like "Changed <this> part of <file>" with a brief description of the largest change made. Ambiguous names make it difficult (like stated above) to revert to an old commit if changes break functionality or cause bugs.

**Comment by AfroChikken** [comment]
I apologize for this, since it was such a small change I didn't think it'd
really matter. Won't do it again.
